language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES=beta

before_install:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

install:
  - composer self-update
  - composer install
