language: php

php:
  - 7.1
  - 7.2

matrix:
  include:
    - php: 7.1
      env: DEPENDENCIES=low
    - php: 7.2
      env: DEPENDENCIES=dev

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; else composer install; fi;
