dist: bionic
language: php

php:
  - '7.2'
  - '7.3'
  - nightly

env: []

matrix:
  include:
    - dist: xenial
      php: '7.2.9'
      env: DEPENDENCIES=low SYMFONY_DEPRECATIONS_HELPER=weak
    - php: '7.4'
      env: CHECK_CS=1
    - php: '7.4'
      env: DEPENDENCIES=dev

  allow_failures:
    - env: DEPENDENCIES=dev

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then composer config platform.php 7.4.99; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; else composer install; fi;

script:
  - if [ "$CHECK_CS" = "1" ]; then ./vendor/bin/php-cs-fixer fix --dry-run; fi;
  - ./vendor/bin/phpunit
