dist: xenial
language: php

php:
  - '7.2'

env: []

matrix:
  include:
    - php: '7.2.9'
      env: DEPENDENCIES=low
    - php: '7.3'
      env: CHECK_CS=1
    - php: '7.4snapshot'
      env: DEPENDENCIES=dev

  allow_failures:
    - env: DEPENDENCIES=dev

before_install:
  - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install:
  - if [ "$DEPENDENCIES" = "low" ]; then composer update --prefer-lowest; else composer install; fi;

script:
  - if [ "$CHECK_CS" = "1" ]; then ./vendor/bin/php-cs-fixer fix --dry-run; fi;
  - ./vendor/bin/phpunit
