name: CI

on:
    pull_request:
    push:

jobs:
    coding-standards:
        name: Coding Standards

        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout code
                uses: 'actions/checkout@v2'
            -
                name: Install PHP
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: none
                    php-version: '8.0'
                    tools: composer
            -
                name: Composer
                uses: 'ramsey/composer-install@v1'
                with:
                    composer-options: '--no-suggest --no-scripts'
            -
                name: PHP CS Fixer
                run: 'vendor/bin/php-cs-fixer fix --dry-run'

    test:
        name: 'PHPUnit ${{ matrix.php-version }}'

        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '7.2'
                    - '7.3'
                    - '8.0'
                    - '8.1'
                dependencies:
                    - stable
                include:
                    - php-version: '7.2.9'
                      dependencies: low
                    - php-version: '7.4'
                      dependencies: dev

        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    php-version: ${{ matrix.php-version }}
                    tools: composer
            -
                name: Remove CS Fixer
                run: composer remove --dev --no-update friendsofphp/php-cs-fixer
            -
                name: Composer for dev dependencies
                if: ${{ matrix.dependencies == 'dev' }}
                run: composer config minimum-stability dev && composer update
            -
                name: Composer for low dependencies
                if: ${{ matrix.dependencies == 'low' }}
                run: composer update --prefer-lowest
            -
                name: Composer for stable dependencies
                if: ${{ matrix.dependencies == 'stable' }}
                run: composer update
            -
                name: PHPUnit
                run: vendor/bin/phpunit
